Llamamos las Librerias que usaremos 

In [ ]:
import os              # Package to use directory command to list files
import numpy as np     # linear algebra
import pandas as pd    # data processing, CSV file I/O (e.g. pd.read_csv)
import seaborn as sns  # Used for plotting the graph
import matplotlib.pyplot as plt
import re

from scipy import stats # for Statistics
from statistics import mean
from sklearn import preprocessing
from sklearn.metrics import accuracy_score
from scipy.stats import norm
from sklearn.preprocessing import StandardScaler
from matplotlib import rcParams
from sklearn.impute import SimpleImputer
%matplotlib inline

Leemos los data sets y miramos el tamaño del data

In [ ]:
data = pd.read_csv('https://raw.githubusercontent.com/sergiakalorth/MachineLearning-CIM-UPC/master/Final%20Project/datasets/Ames%20Housing%20Price/train.csv')
test = pd.read_csv('https://raw.githubusercontent.com/sergiakalorth/MachineLearning-CIM-UPC/master/Final%20Project/datasets/Ames%20Housing%20Price/test.csv')


print(data.shape)
data.head(946)



(1460, 81)


Id  MSSubClass MSZoning  ...  SaleType  SaleCondition SalePrice
0      1          60       RL  ...        WD         Normal    208500
1      2          20       RL  ...        WD         Normal    181500
2      3          60       RL  ...        WD         Normal    223500
3      4          70       RL  ...        WD        Abnorml    140000
4      5          60       RL  ...        WD         Normal    250000
..   ...         ...      ...  ...       ...            ...       ...
941  942          60       RL  ...        WD         Normal    214000
942  943          90       RL  ...       Oth        Abnorml    150000
943  944          90       RL  ...        WD         Normal    143000
944  945          20       RL  ...       COD        Abnorml    137500
945  946          50       RM  ...        WD         Normal    124900

[946 rows x 81 columns]

Mostramos Todos los Nans del Data

In [ ]:
totalt = data.isnull().sum().sort_values(ascending=False)
percent = (data.isnull().sum()/data.isnull().count()).sort_values(ascending=False)
missing_dataX = pd.concat([totalt, percent], axis=1, keys=['Total', 'Percent'])
missing_dataX.head(20)

Total   Percent
PoolQC         1453  0.995205
MiscFeature    1406  0.963014
Alley          1369  0.937671
Fence          1179  0.807534
FireplaceQu     690  0.472603
LotFrontage     259  0.177397
GarageCond       81  0.055479
GarageType       81  0.055479
GarageYrBlt      81  0.055479
GarageFinish     81  0.055479
GarageQual       81  0.055479
BsmtExposure     38  0.026027
BsmtFinType2     38  0.026027
BsmtFinType1     37  0.025342
BsmtCond         37  0.025342
BsmtQual         37  0.025342
MasVnrArea        8  0.005479
MasVnrType        8  0.005479
Electrical        1  0.000685
Utilities         0  0.000000

Configuramos para poder mas columnas y mas filas del data

In [ ]:
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 300)
data

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0        1          60       RL         65.0     8450   Pave   NaN      Reg   
1        2          20       RL         80.0     9600   Pave   NaN      Reg   
2        3          60       RL         68.0    11250   Pave   NaN      IR1   
3        4          70       RL         60.0     9550   Pave   NaN      IR1   
4        5          60       RL         84.0    14260   Pave   NaN      IR1   
...    ...         ...      ...          ...      ...    ...   ...      ...   
1455  1456          60       RL         62.0     7917   Pave   NaN      Reg   
1456  1457          20       RL         85.0    13175   Pave   NaN      Reg   
1457  1458          70       RL         66.0     9042   Pave   NaN      Reg   
1458  1459          20       RL         68.0     9717   Pave   NaN      Reg   
1459  1460          20       RL         75.0     9937   Pave   NaN      Reg   

     LandContour Utilities LotConfig LandSlope Neighborhood Condition1  \
0            Lvl    AllPub    Inside       Gtl      CollgCr       Norm   
1            Lvl    AllPub       FR2       Gtl      Veenker      Feedr   
2            Lvl    AllPub    Inside       Gtl      CollgCr       Norm   
3            Lvl    AllPub    Corner       Gtl      Crawfor       Norm   
4            Lvl    AllPub       FR2       Gtl      NoRidge       Norm   
...          ...       ...       ...       ...          ...        ...   
1455         Lvl    AllPub    Inside       Gtl      Gilbert       Norm   
1456         Lvl    AllPub    Inside       Gtl       NWAmes       Norm   
1457         Lvl    AllPub    Inside       Gtl      Crawfor       Norm   
1458         Lvl    AllPub    Inside       Gtl        NAmes       Norm   
1459         Lvl    AllPub    Inside       Gtl      Edwards       Norm   

     Condition2 BldgType HouseStyle  OverallQual  OverallCond  YearBuilt  \
0          Norm     1Fam     2Story            7            5       2003   
1          Norm     1Fam     1Story            6            8       1976   
2          Norm     1Fam     2Story            7            5       2001   
3          Norm     1Fam     2Story            7            5       1915   
4          Norm     1Fam     2Story            8            5       2000   
...         ...      ...        ...          ...          ...        ...   
1455       Norm     1Fam     2Story            6            5       1999   
1456       Norm     1Fam     1Story            6            6       1978   
1457       Norm     1Fam     2Story            7            9       1941   
1458       Norm     1Fam     1Story            5            6       1950   
1459       Norm     1Fam     1Story            5            6       1965   

      YearRemodAdd RoofStyle RoofMatl Exterior1st Exterior2nd MasVnrType  \
0             2003     Gable  CompShg     VinylSd     VinylSd    BrkFace   
1             1976     Gable  CompShg     MetalSd     MetalSd       None   
2             2002     Gable  CompShg     VinylSd     VinylSd    BrkFace   
3             1970     Gable  CompShg     Wd Sdng     Wd Shng       None   
4             2000     Gable  CompShg     VinylSd     VinylSd    BrkFace   
...            ...       ...      ...         ...         ...        ...   
1455          2000     Gable  CompShg     VinylSd     VinylSd       None   
1456          1988     Gable  CompShg     Plywood     Plywood      Stone   
1457          2006     Gable  CompShg     CemntBd     CmentBd       None   
1458          1996       Hip  CompShg     MetalSd     MetalSd       None   
1459          1965     Gable  CompShg     HdBoard     HdBoard       None   

      MasVnrArea ExterQual ExterCond Foundation BsmtQual BsmtCond  \
0          196.0        Gd        TA      PConc       Gd       TA   
1            0.0        TA        TA     CBlock       Gd       TA   
2          162.0        Gd        TA      PConc       Gd       TA   
3            0.0        TA        TA     BrkTil       TA       Gd   

Eliminamos las columnas que tengan mayor cantidad de NaNs

In [ ]:

df1 = data.drop(['PoolQC','MiscFeature','Alley','Fence','FireplaceQu','LotFrontage'], axis=1)


Eliminamos las filas correspondientes para obtener las mismas dimenciones en data y test, es decir, para tener la misma cantidad de variables una vez se trabaje con los datos categoricos.

In [ ]:
df1 = df1.drop([29,120,185,198,267,268,271,304,398,548,635,760,883,944,1003,1024,1031,1152,1187,1230,1248,1275,1298,1321,1349,1440], axis=0)


Ploteamos para poder observar que las variables que hemos eliminado no esten

In [ ]:
df1

Id  MSSubClass MSZoning  LotArea Street LotShape LandContour  \
0        1          60       RL     8450   Pave      Reg         Lvl   
1        2          20       RL     9600   Pave      Reg         Lvl   
2        3          60       RL    11250   Pave      IR1         Lvl   
3        4          70       RL     9550   Pave      IR1         Lvl   
4        5          60       RL    14260   Pave      IR1         Lvl   
...    ...         ...      ...      ...    ...      ...         ...   
1455  1456          60       RL     7917   Pave      Reg         Lvl   
1456  1457          20       RL    13175   Pave      Reg         Lvl   
1457  1458          70       RL     9042   Pave      Reg         Lvl   
1458  1459          20       RL     9717   Pave      Reg         Lvl   
1459  1460          20       RL     9937   Pave      Reg         Lvl   

     Utilities LotConfig LandSlope Neighborhood Condition1 Condition2  \
0       AllPub    Inside       Gtl      CollgCr       Norm       Norm   
1       AllPub       FR2       Gtl      Veenker      Feedr       Norm   
2       AllPub    Inside       Gtl      CollgCr       Norm       Norm   
3       AllPub    Corner       Gtl      Crawfor       Norm       Norm   
4       AllPub       FR2       Gtl      NoRidge       Norm       Norm   
...        ...       ...       ...          ...        ...        ...   
1455    AllPub    Inside       Gtl      Gilbert       Norm       Norm   
1456    AllPub    Inside       Gtl       NWAmes       Norm       Norm   
1457    AllPub    Inside       Gtl      Crawfor       Norm       Norm   
1458    AllPub    Inside       Gtl        NAmes       Norm       Norm   
1459    AllPub    Inside       Gtl      Edwards       Norm       Norm   

     BldgType HouseStyle  OverallQual  OverallCond  YearBuilt  YearRemodAdd  \
0        1Fam     2Story            7            5       2003          2003   
1        1Fam     1Story            6            8       1976          1976   
2        1Fam     2Story            7            5       2001          2002   
3        1Fam     2Story            7            5       1915          1970   
4        1Fam     2Story            8            5       2000          2000   
...       ...        ...          ...          ...        ...           ...   
1455     1Fam     2Story            6            5       1999          2000   
1456     1Fam     1Story            6            6       1978          1988   
1457     1Fam     2Story            7            9       1941          2006   
1458     1Fam     1Story            5            6       1950          1996   
1459     1Fam     1Story            5            6       1965          1965   

     RoofStyle RoofMatl Exterior1st Exterior2nd MasVnrType  MasVnrArea  \
0        Gable  CompShg     VinylSd     VinylSd    BrkFace       196.0   
1        Gable  CompShg     MetalSd     MetalSd       None         0.0   
2        Gable  CompShg     VinylSd     VinylSd    BrkFace       162.0   
3        Gable  CompShg     Wd Sdng     Wd Shng       None         0.0   
4        Gable  CompShg     VinylSd     VinylSd    BrkFace       350.0   
...        ...      ...         ...         ...        ...         ...   
1455     Gable  CompShg     VinylSd     VinylSd       None         0.0   
1456     Gable  CompShg     Plywood     Plywood      Stone       119.0   
1457     Gable  CompShg     CemntBd     CmentBd       None         0.0   
1458       Hip  CompShg     MetalSd     MetalSd       None         0.0   
1459     Gable  CompShg     HdBoard     HdBoard       None         0.0   

     ExterQual ExterCond Foundation BsmtQual BsmtCond BsmtExposure  \
0           Gd        TA      PConc       Gd       TA           No   
1           TA        TA     CBlock       Gd       TA           Gd   
2           Gd        TA      PConc       Gd       TA           Mn   
3           TA        TA     BrkTil       TA       Gd           No   
4           Gd        TA      PConc       Gd       TA           Av   
...     

Determinamos cuales son las columnas que tienen dataos categoricos

In [ ]:
pd.set_option('display.max_rows', 300)
print(df1.dtypes)

Id                 int64
MSSubClass         int64
MSZoning          object
LotArea            int64
Street            object
LotShape          object
LandContour       object
Utilities         object
LotConfig         object
LandSlope         object
Neighborhood      object
Condition1        object
Condition2        object
BldgType          object
HouseStyle        object
OverallQual        int64
OverallCond        int64
YearBuilt          int64
YearRemodAdd       int64
RoofStyle         object
RoofMatl          object
Exterior1st       object
Exterior2nd       object
MasVnrType        object
MasVnrArea       float64
ExterQual         object
ExterCond         object
Foundation        object
BsmtQual          object
BsmtCond          object
BsmtExposure      object
BsmtFinType1      object
BsmtFinSF1         int64
BsmtFinType2      object
BsmtFinSF2         int64
BsmtUnfSF          int64
TotalBsmtSF        int64
Heating           object
HeatingQC         object
CentralAir        object


Eliminamos los NaNs de la data

In [ ]:
df = df1
df= df.interpolate(method="pad")

totalt = df.isnull().sum().sort_values(ascending=False)
percent = (df.isnull().sum()/df.isnull().count()).sort_values(ascending=False)
missing_dataX = pd.concat([totalt, percent], axis=1, keys=['Total', 'Percent'])
missing_dataX.head(80)
# df = df.fillna(value= 'TA')
# df.head(10)
print(df.shape)

(1434, 75)


Verificamos que se hayan eliminado 

In [ ]:
totalt1 = df.isnull().sum().sort_values(ascending=False)
percent1 = (df.isnull().sum()/df.isnull().count()).sort_values(ascending=False)
missing_dataX = pd.concat([totalt1, percent1], axis=1, keys=['Total', 'Percent'])
missing_dataX.head(20)

Total  Percent
SalePrice         0      0.0
YearRemodAdd      0      0.0
RoofMatl          0      0.0
Exterior1st       0      0.0
Exterior2nd       0      0.0
MasVnrType        0      0.0
MasVnrArea        0      0.0
ExterQual         0      0.0
ExterCond         0      0.0
Foundation        0      0.0
BsmtQual          0      0.0
BsmtCond          0      0.0
BsmtExposure      0      0.0
BsmtFinType1      0      0.0
BsmtFinSF1        0      0.0
BsmtFinType2      0      0.0
BsmtFinSF2        0      0.0
RoofStyle         0      0.0
YearBuilt         0      0.0
TotalBsmtSF       0      0.0

volvemos a mirar el tipo de los datos en cada columna para asegurarnos cuales son los datos categoricos 

In [ ]:
print(df.dtypes)

Id                 int64
MSSubClass         int64
MSZoning          object
LotArea            int64
Street            object
LotShape          object
LandContour       object
Utilities         object
LotConfig         object
LandSlope         object
Neighborhood      object
Condition1        object
Condition2        object
BldgType          object
HouseStyle        object
OverallQual        int64
OverallCond        int64
YearBuilt          int64
YearRemodAdd       int64
RoofStyle         object
RoofMatl          object
Exterior1st       object
Exterior2nd       object
MasVnrType        object
MasVnrArea       float64
ExterQual         object
ExterCond         object
Foundation        object
BsmtQual          object
BsmtCond          object
BsmtExposure      object
BsmtFinType1      object
BsmtFinSF1         int64
BsmtFinType2      object
BsmtFinSF2         int64
BsmtUnfSF          int64
TotalBsmtSF        int64
Heating           object
HeatingQC         object
CentralAir        object


Separamos el data en entradas y salida para posteriormenet trabajar con los datos categoricos de las variables de entrada

In [ ]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values
print(X[0,:])
# print(df.dtypes)

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
# print(X.shape)
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [2,4,5,6,7,8,9,10,11,12,13,14,19,20,21,22,23,25,26,27,28,29,30,31,33,37,38,39,40,51,53,55])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

ct2 = ColumnTransformer(transformers=[('encoder2', OneHotEncoder(), [214, 217, 218, 219, 229, 230])], remainder='passthrough')
X = np.array(ct2.fit_transform(X))
# print(X)
print(X.shape)
print(X[17,:])
# print(y[17])

[1 60 'RL' 8450 'Pave' 'Reg' 'Lvl' 'AllPub' 'Inside' 'Gtl' 'CollgCr'
 'Norm' 'Norm' '1Fam' '2Story' 7 5 2003 2003 'Gable' 'CompShg' 'VinylSd'
 'VinylSd' 'BrkFace' 196.0 'Gd' 'TA' 'PConc' 'Gd' 'TA' 'No' 'GLQ' 706
 'Unf' 0 150 856 'GasA' 'Ex' 'Y' 'SBrkr' 856 854 0 1710 1 0 2 1 3 1 'Gd' 8
 'Typ' 0 'Attchd' 2003.0 'RFn' 2 548 'TA' 'TA' 'Y' 0 61 0 0 0 0 0 2 2008
 'WD' 'Normal']
(1434, 254)
[0.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0
 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 1.0
 0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 1.0 0.0 0.0 0.0 0.0 1.0 1.0 0.0 0.0 0.0
 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0
 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0
 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0
 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
 0.0 1.0 0.0 0.0 0.0 0.0 1.0

Aplicamos el metedo de RandomForest Regression, debido a la gran cantidad de datos categoricos elegimos este metodo por ensima de una regresion, ademas de no requerir estandarisar los datos despues de trabajar con las variables categoricas 

In [ ]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
# n_estimators = numero de arboles.
regressor.fit(X, y)

# y = sc.fit_transform(y)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=10, n_jobs=None, oob_score=False,
                      random_state=0, verbose=0, warm_start=False)

Plotemos X. Y

In [ ]:
print (X)
print (y)

[[0.0 1.0 0.0 ... 0 2 2008]
 [0.0 1.0 0.0 ... 0 5 2007]
 [0.0 1.0 0.0 ... 0 9 2008]
 ...
 [0.0 1.0 0.0 ... 2500 5 2010]
 [0.0 0.0 1.0 ... 0 4 2010]
 [1.0 0.0 0.0 ... 0 6 2008]]
[208500 181500 223500 ... 266500 142125 147500]


Buscamos los Nans en el Test

In [ ]:
totalt1 = test.isnull().sum().sort_values(ascending=False)
percent1 = (test.isnull().sum()/test.isnull().count()).sort_values(ascending=False)
missing_data1X = pd.concat([totalt1, percent1], axis=1, keys=['Total', 'Percent'])
missing_data1X.head(80)


Total   Percent
PoolQC          1456  0.997944
MiscFeature     1408  0.965045
Alley           1352  0.926662
Fence           1169  0.801234
FireplaceQu      730  0.500343
LotFrontage      227  0.155586
GarageCond        78  0.053461
GarageQual        78  0.053461
GarageYrBlt       78  0.053461
GarageFinish      78  0.053461
GarageType        76  0.052090
BsmtCond          45  0.030843
BsmtQual          44  0.030158
BsmtExposure      44  0.030158
BsmtFinType1      42  0.028787
BsmtFinType2      42  0.028787
MasVnrType        16  0.010966
MasVnrArea        15  0.010281
MSZoning           4  0.002742
BsmtHalfBath       2  0.001371
Utilities          2  0.001371
Functional         2  0.001371
BsmtFullBath       2  0.001371
BsmtFinSF2         1  0.000685
BsmtFinSF1         1  0.000685
Exterior2nd        1  0.000685
BsmtUnfSF          1  0.000685
TotalBsmtSF        1  0.000685
SaleType           1  0.000685
Exterior1st        1  0.000685
KitchenQual        1  0.000685
GarageArea         1  0.000685
GarageCars         1  0.000685
HouseStyle         0  0.000000
LandSlope          0  0.000000
MSSubClass         0  0.000000
LotArea            0  0.000000
Street             0  0.000000
LotShape           0  0.000000
LandContour        0  0.000000
LotConfig          0  0.000000
Neighborhood       0  0.000000
BldgType           0  0.000000
Condition1         0  0.000000
Condition2         0  0.000000
RoofMatl           0  0.000000
RoofStyle          0  0.000000
YearRemodAdd       0  0.000000
YearBuilt          0  0.000000
OverallCond        0  0.000000
OverallQual        0  0.000000
SaleCondition      0  0.000000
Heating            0  0.000000
ExterQual          0  0.000000
TotRmsAbvGrd       0  0.000000
YrSold             0  0.000000
MoSold             0  0.000000
MiscVal            0  0.000000
PoolArea           0  0.000000
ScreenPorch        0  0.000000
3SsnPorch          0  0.000000
EnclosedPorch      0  0.000000
OpenPorchSF        0  0.000000
WoodDeckSF         0  0.000000
PavedDrive         0  0.000000
Fireplaces         0  0.000000
KitchenAbvGr       0  0.000000
ExterCond          0  0.000000
BedroomAbvGr       0  0.000000
HalfBath           0  0.000000
FullBath           0  0.000000
GrLivArea          0  0.000000
LowQualFinSF       0  0.000000
2ndFlrSF           0  0.000000
1stFlrSF           0  0.000000
Electrical         0  0.000000
CentralAir         0  0.000000
HeatingQC          0  0.000000
Foundation         0  0.000000
Id                 0  0.000000

Quitamos nuevamente las Columnas que tengan la mayor cantidad de NaNs 

In [ ]:
df3 = test.drop(['PoolQC','MiscFeature','Alley','Fence','FireplaceQu','LotFrontage'], axis=1)
df3.head()

Id  MSSubClass MSZoning  LotArea Street LotShape LandContour Utilities  \
0  1461          20       RH    11622   Pave      Reg         Lvl    AllPub   
1  1462          20       RL    14267   Pave      IR1         Lvl    AllPub   
2  1463          60       RL    13830   Pave      IR1         Lvl    AllPub   
3  1464          60       RL     9978   Pave      IR1         Lvl    AllPub   
4  1465         120       RL     5005   Pave      IR1         HLS    AllPub   

  LotConfig LandSlope Neighborhood Condition1 Condition2 BldgType HouseStyle  \
0    Inside       Gtl        NAmes      Feedr       Norm     1Fam     1Story   
1    Corner       Gtl        NAmes       Norm       Norm     1Fam     1Story   
2    Inside       Gtl      Gilbert       Norm       Norm     1Fam     2Story   
3    Inside       Gtl      Gilbert       Norm       Norm     1Fam     2Story   
4    Inside       Gtl      StoneBr       Norm       Norm   TwnhsE     1Story   

   OverallQual  OverallCond  YearBuilt  YearRemodAdd RoofStyle RoofMatl  \
0            5            6       1961          1961     Gable  CompShg   
1            6            6       1958          1958       Hip  CompShg   
2            5            5       1997          1998     Gable  CompShg   
3            6            6       1998          1998     Gable  CompShg   
4            8            5       1992          1992     Gable  CompShg   

  Exterior1st Exterior2nd MasVnrType  MasVnrArea ExterQual ExterCond  \
0     VinylSd     VinylSd       None         0.0        TA        TA   
1     Wd Sdng     Wd Sdng    BrkFace       108.0        TA        TA   
2     VinylSd     VinylSd       None         0.0        TA        TA   
3     VinylSd     VinylSd    BrkFace        20.0        TA        TA   
4     HdBoard     HdBoard       None         0.0        Gd        TA   

  Foundation BsmtQual BsmtCond BsmtExposure BsmtFinType1  BsmtFinSF1  \
0     CBlock       TA       TA           No          Rec       468.0   
1     CBlock       TA       TA           No          ALQ       923.0   
2      PConc       Gd       TA           No          GLQ       791.0   
3      PConc       TA       TA           No          GLQ       602.0   
4      PConc       Gd       TA           No          ALQ       263.0   

  BsmtFinType2  BsmtFinSF2  BsmtUnfSF  TotalBsmtSF Heating HeatingQC  \
0          LwQ       144.0      270.0        882.0    GasA        TA   
1          Unf         0.0      406.0       1329.0    GasA        TA   
2          Unf         0.0      137.0        928.0    GasA        Gd   
3          Unf         0.0      324.0        926.0    GasA        Ex   
4          Unf         0.0     1017.0       1280.0    GasA        Ex   

  CentralAir Electrical  1stFlrSF  2ndFlrSF  LowQualFinSF  GrLivArea  \
0          Y      SBrkr       896         0             0        896   
1          Y      SBrkr      1329         0             0       1329   
2          Y      SBrkr       928       701             0       1629   
3          Y      SBrkr       926       678             0       1604   
4          Y      SBrkr      1280         0             0       1280   

   BsmtFullBath  BsmtHalfBath  FullBath  HalfBath  BedroomAbvGr  KitchenAbvGr  \
0           0.0           0.0         1         0             2             1   
1           0.0           0.0         1         1             3             1   
2           0.0           0.0         2         1             3             1   
3           0.0           0.0         2         1             3             1   
4           0.0           0.0         2         0             2             1   

  KitchenQual  TotRmsAbvGrd Functional  Fireplaces GarageType  GarageYrBlt  \
0          TA             5        Typ           0     Attchd       1961.0   
1          Gd             6        Typ           0     Attchd       1958.0   
2          TA             6        Typ           1     Attchd       1997.0   
3          Gd             7        Typ           1     Attchd      

Aplicamos el Metodo de interpolacion para quitar los nans del Test

In [ ]:
df4 = df3
df4= df4.interpolate(method="pad")
pd.set_option('display.max_rows', 100)
totalt1 = df4.isnull().sum().sort_values(ascending=False)
percent1 = (df4.isnull().sum()/df4.isnull().count()).sort_values(ascending=False)
missing_data1X = pd.concat([totalt1, percent1], axis=1, keys=['Total', 'Percent'])
missing_data1X.head(80)
print(df4.shape)

(1459, 74)


Miramos el tipo de dato que tienen las Columnas del Test

In [ ]:
print(df4.dtypes)

Id                 int64
MSSubClass         int64
MSZoning          object
LotArea            int64
Street            object
LotShape          object
LandContour       object
Utilities         object
LotConfig         object
LandSlope         object
Neighborhood      object
Condition1        object
Condition2        object
BldgType          object
HouseStyle        object
OverallQual        int64
OverallCond        int64
YearBuilt          int64
YearRemodAdd       int64
RoofStyle         object
RoofMatl          object
Exterior1st       object
Exterior2nd       object
MasVnrType        object
MasVnrArea       float64
ExterQual         object
ExterCond         object
Foundation        object
BsmtQual          object
BsmtCond          object
BsmtExposure      object
BsmtFinType1      object
BsmtFinSF1       float64
BsmtFinType2      object
BsmtFinSF2       float64
BsmtUnfSF        float64
TotalBsmtSF      float64
Heating           object
HeatingQC         object
CentralAir        object


Trabajamos con lso datos categoricos del Test y comprobamos que tengamos la misma cantidad de columnas que el Data

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
# print(df4.shape)
# 
ct3 = ColumnTransformer(transformers=[('encoder3', OneHotEncoder(), [2,4,5,6,7,8,9,10,11,12,13,14,19,20,21,22,23,25,26,27,28,29,30,31,33,37,38,39,40,51,53,55])], remainder='passthrough')
X_test = np.array(ct3.fit_transform(df4))
print(X_test.shape)


ct4 = ColumnTransformer(transformers=[('encoder4', OneHotEncoder(), [213, 216, 217, 218, 228, 229])], remainder='passthrough')
X_test = np.array(ct4.fit_transform(X_test))
print(X_test)
print(X_test.shape)

(1459, 230)
[[0.0 0.0 1.0 ... 0 6 2010]
 [0.0 0.0 1.0 ... 12500 6 2010]
 [1.0 0.0 0.0 ... 0 3 2010]
 ...
 [0.0 0.0 1.0 ... 0 9 2006]
 [0.0 0.0 1.0 ... 700 7 2006]
 [1.0 0.0 0.0 ... 0 11 2006]]
(1459, 254)


Ejecutamos la Prediccion 

In [ ]:
y_pred = regressor.predict(X_test)

Mostramos la Prediccion 

In [ ]:
print (y_pred)

[128900.  145575.  177892.  ... 160430.  104600.  250660.5]
